language: ruby
rvm:
  - "2.3.8"
services: mongodb
script:
  - bundle exec bundle-audit check --update --ignore CVE-2020-5267 CVE-2020-8166 CVE-2020-8164 CVE-2020-15169 CVE-2020-8163 CVE-2020-8167 CVE-2020-8165 CVE-2020-8184 CVE-2020-8161
  - bundle exec rake
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
