language: ruby
rvm:
  - "2.3.8"
services: mongodb
script:
  - bundle exec bundle-audit check --update --ignore CVE-2020-10663 CVE-2019-15587 CVE-2020-7595 CVE-2019-13117 CVE-2019-16782 CVE-2020-8130 CVE-2019-16892
  - bundle exec rake
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
