language: ruby
rvm:
  - "2.2.7"
services: mongodb
script:
  - bundle exec bundle-audit check --update
  - bundle exec rake
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
